export type EnemArea = {
    CienciaHumana: 'Ciências Humanas'
    CienciaNatureza: 'Ciências da Natureza'
    Linguagem: 'Linguagens'
    Matematica: 'Matemática'
  }
  
  export type Materias = {
    Historia: 'História'
    Geografia: 'Geografia'
    Filosofia: 'Filosofia'
    Sociologia: 'Sociologia'
    Atualidade: 'Atualidade'
    Quimica: 'Química'
    Fisica: 'Física'
    Biologia: 'Biologia'
    LinguaPortuguesa: 'Língua Portuguesa'
    Literatura: 'Literatura'
    LinguaEstrangeiras: 'Língua Estrangeiras'
    Artes: 'Artes'
    EducacaFisica: 'Educação Física'
    TecnologiaInformacaoComunicacao: 'Tecnologia da Informação e Comunicação'
    Matematica: 'Matemática'
  }
  
  export type Frentes = {
    BotanicaEcologia: 'Botânica e Ecologia'
    FisiologiaAnimalOrigemVida: 'Fisiologia animal e origem da vida'
    MetabolismoCelularBioquimicaGenetica: 'Metabolismo celular, Bioquímica e Genética'
    Eletromagnetismo: 'Eletromagnetismo'
    Mecanica: 'Mecânica'
    OpticaTermica: 'Óptica e Térmica'
    AritmeticaAlgebra: 'Aritmética e Algebra'
    FinanceiraTrigonometria: 'Financeira e Trigonometria'
    Geometria: 'Geometria'
    FisicoQuemica: 'Físico-Química'
    QuimicaGeral: 'Química Geral'
    QuimicaOrganica: 'Química Orgânica'
    Atualidade: 'Atualidade'
    Filosofia: 'Filosofia'
    Sociologia: 'Sociologia'
    GeografiaBrasil: 'Geografia do Brasil'
    GeografiaGeral: 'Geografia Geral'
    HistoriaBrasil: 'História do Brasil'
    HistoriaGeral: 'História Geral'
    Artes: 'Artes'
    Espanhol: 'Espanhol'
    Gramatica: 'Gramática'
    Ingles: 'Inglês'
    Literatura: 'Literatura'
    LeituraProducaoTexto: 'Leitura e Produção de Texto'
    TecnologiasInformacaoComunicacao: 'Tecnologias da Informação e Comunicação'
  }
  