export const EnemArea = ['Ciências Humanas', 'Ciências da Natureza', 'Linguagens', 'Matemática']

export const Materias = [
  'História',
  'Geografia',
  'Filosofia',
  'Sociologia',
  'Química',
  'Física',
  'Biologia',
  'Língua Portuguesa',
  'Literatura',
  'Artes',
  'Educação Física',
  'Tecnologia da Informação e Comunicação',
  'Matemática',
  'Atualidade',
]

export const frentes = [
  'Botânica e ecologia',
  'Fisiologia animal e origem da vida',
  'Metabolismo celular, Bioquímica e Genética',
  'Eletromagnetismo',
  'Mecânica',
  'Óptica e Térmica',
  'Aritmética e Algebra',
  'Financeira e Trigonometria',
  'Geometria',
  'Físico-Química',
  'Química Geral',
  'Química Orgânica',
  'Atualidade',
  'Filosofia',
  'Sociologia',
  'Geografia do Brasil',
  'Geografia Geral',
  'História do Brasil',
  'História Geral',
  'Artes',
  'Espanhol',
  'Gramática',
  'Inglês',
  'Literatura',
  'Leitura e Produção de Texto',
  'Tecnologias da Informação e Comunicação',
]
